[project]
name = 'Decentralized-Travel-Booking-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.accommodation]
path = 'contracts/accommodation.clar'
clarity_version = 2
epoch = 2.5

[contracts.loyalty-program]
path = 'contracts/loyalty-program.clar'
clarity_version = 2
epoch = 2.5

[contracts.review]
path = 'contracts/review.clar'
clarity_version = 2
epoch = 2.5

[contracts.transportation]
path = 'contracts/transportation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
